version: "3.5"

services:
  app:
    build: .
    container_name: expense_list_app
    volumes:
      - .:/home/node/app
    ports:
      - 5000:5000
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
